# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zQtFGMvdfRpos3zv_NwX6BN3u3kIlxFT
"""

data = '/content/drive/MyDrive/Colab Notebooks/New folder/all_data.csv'
import pandas as pd

df = pd.read_csv(data)
print(df.head())

df.Country.unique()

chile = df[df['Country'] == 'Chile']
china = df[df['Country'] == 'China']
germany = df[df['Country'] == 'Germany']
mexico = df[df['Country'] == 'Mexico']
usa = df[df['Country'] == 'United States of America']
zim = df[df['Country'] == 'Zimbabwe']

import matplotlib.pyplot as plt
import seaborn as sns

sns.lineplot(chile['Year'],chile['GDP'],label ='chile')
sns.lineplot(china['Year'],china['GDP'],label = 'china')
sns.lineplot(germany['Year'],germany['GDP'],label = 'germany')
sns.lineplot(mexico['Year'],mexico['GDP'],label = 'mexico')
sns.lineplot(usa['Year'],usa['GDP'],label = 'usa')
sns.lineplot(zim['Year'],zim['GDP'],label = 'zim')
plt.legend()
plt.show()

sns.lineplot(chile['Year'],chile['Life expectancy at birth (years)'],label ='chile')
sns.lineplot(china['Year'],china['Life expectancy at birth (years)'],label = 'china')
sns.lineplot(germany['Year'],germany['Life expectancy at birth (years)'],label = 'germany')
sns.lineplot(mexico['Year'],mexico['Life expectancy at birth (years)'],label = 'mexico')
sns.lineplot(usa['Year'],usa['Life expectancy at birth (years)'],label = 'usa')
sns.lineplot(zim['Year'],zim['Life expectancy at birth (years)'],label = 'zim')
plt.legend()
plt.show()

sns.scatterplot(df['GDP'],df['Life expectancy at birth (years)'],hue = df['Country'])
plt.show()

print('avg life expectancy of chile: {}'.format(chile['Life expectancy at birth (years)'].mean()))
print('avg life expectancy of china: {}'.format(china['Life expectancy at birth (years)'].mean()))
print('avg life expectancy of germany: {}'.format(germany['Life expectancy at birth (years)'].mean()))
print('avg life expectancy of mexico: {}'.format(mexico['Life expectancy at birth (years)'].mean()))
print('avg life expectancy of usa: {}'.format(usa['Life expectancy at birth (years)'].mean()))
print('avg life expectancy of zim: {}'.format(zim['Life expectancy at birth (years)'].mean()))

plt.figure(figsize=(10,10))
sns.boxplot(df['Country'],df['Life expectancy at birth (years)'])

plt.show()

plt.figure(figsize=(10,15))
sns.violinplot(df['Country'],df['Life expectancy at birth (years)'])
plt.show()



















